brew install --cask  tableplus
brew install --cask  google-chrome
brew install --cask  homebrew/cask-versions/firefox-developer-edition
brew install --cask  slack
brew install --cask  alfred
brew install --cask  rectangle
brew install --cask  homebrew/cask-drivers/logitech-options
brew install --cask  appcleaner
brew install --cask  signal
brew install --cask  zoomus
brew install --cask  iterm2
brew install --cask  visual-studio-code
brew install --cask  postman
brew install --cask  spotify
